spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: https://config-cloud-server.herokuapp.com/
  redis:
    host: localhost
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 30000
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: https://discovery-eureka-server.herokuapp.com/eureka/
  instance:
    hostname: localhost
    
resilience4j:
  ratelimiter:
    instances:
      basic:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
      timeout:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms
      fallback:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms
  retry:
    instances:
      basic:
        maxRetryAttempts: 5
        waitDuration: 2s
      throwingException:
        maxRetryAttempts: 5
        retryExceptions:
          - java.lang.Exception
        waitDuration: 2s
      ignoreException:
        maxRetryAttempts: 5
        ignoreExceptions:
          - java.lang.Exception
        waitDuration: 2s
