spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  redis:
    host: localhost
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 30000
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 0

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
resilience4j:
  ratelimiter:
    instances:
      basic:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
      timeout:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms
      fallback:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms
