spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
